### ISSUE TITLE
Move to php7

### ISSUE THREAD

**Issue by freaktechnik** [mozillach/mozilla.ch-docker#3]
We should consider moving the container to php 7.
@colinfrei is everything we use php7 ready? I know twig works with php7 but that's about it.

**Comment by MichaelKohler** [comment]
I can create another droplet to test this if needed.

**Comment by freaktechnik** [comment]
Using php 7 SeemsGood to me locally.

**Comment by J0WI** [comment]
Any thoughts about HHVM?

**Comment by MichaelKohler** [comment]
Improvement vs. effort? no idea..

**Comment by colinfrei** [comment]
Re HHVM: with one of our big projects we compared PHP7 with HHVM, though it wasn't the newest HHVM version. Performance was comparable.

Overall, I'm not sure performance is an issue here anyway, so moving to HHVM would be more of a 'for fun' project in my eyes.
