### ISSUE TITLE
Automate container builds

### ISSUE THREAD

**Issue by freaktechnik** [mozillach/mozilla.ch-docker#4]
It would be nice to build the container whenever we push to the release branch of mozillach/mozilla.ch. There are two ways to achieve this:
- Merge the docker config into the mozillach/mozilla.ch repo.
- Use a tool like travis-ci.org to build the container on pushes to the release branch.

**Comment by MichaelKohler** [comment]
That would be great, indeed! If it's enough to merge the Dockerfile to the main repo, I'd go for that one!

**Comment by freaktechnik** [comment]
We'd have to merge everything in this repo, since we need all the files. But then we already have a Vagrantfile and some other random things that aren't used directly for the docker container in there, too. We could also add a subfolder for all the docker container relevant files.

**Comment by MichaelKohler** [comment]
I don't mind to have those 3 files additionally in the root of the repo. If we want, we can also have a docker subfolder, this might get confusing though, since we have other folders too which are actual content.

**Comment by MichaelKohler** [comment]
And since everything currently in the root of the mozilla.ch repo is to bootstrap the content, it kinda would make sense to have docker there as well, wouldn't it?

**Comment by freaktechnik** [comment]
Yeah, but one deployment strategy thing has its own files deeper in the folder structure, too. But yeah, I don't mind, tbh.

**Comment by J0WI** [comment]
What about Docker Hup?

**Comment by freaktechnik** [comment]
Docker hub requires the Dockerfile to be in the same repo as you want to push to, which is what the first option describes.

**Comment by colinfrei** [comment]
Wouldn't you need the vendors in the repo as well?
I'd tend to lean towards using TravisCI

**Comment by freaktechnik** [comment]
No, the docker container provisions itself whenever it is ran, which will download the vendor deps.

**Comment by MichaelKohler** [comment]
So, what are our options regarding automating pushes to the Docker Hub? For now we would need to inform the Community IT team to re-pull and restart the container, but that should be okay. They're working on a solution for that.

**Comment by freaktechnik** [comment]
See the travis branch in mozillach/mozilla.ch where colin has been playing around with autmating it with travis in the last travis step.

**Comment by freaktechnik** [comment]
This is fixed in mozillach/mozilla.ch
