### ISSUE TITLE
Add HTTPS support

### ISSUE THREAD

**Issue by MichaelKohler** [mozillach/mozilla.ch-docker#6]
Since the instance on Community PaaS will require SSL, we need to have SSL. Otherwise we get some good mixed-content-blocking as currently seen on https://mozillach.paas.mozilla.community/ .

What are our options here? I don't think we need an official Mozilla cert, since we have let's encrypt. Can we easily add this to our instance?

We need to solve this before we can move forward with https://github.com/mozillach/mozilla.ch/issues/17 .

**Comment by J0WI** [comment]
There is a Docker Container for Let's Encrypt: https://github.com/letsencrypt/letsencrypt/blob/master/Dockerfile

EDIT: https://mozillach.paas.mozilla.community/ already got a valid cert, so we just have to fix the base url, don't we?

**Comment by MichaelKohler** [comment]
oh right, didn't notice that.. then this is what we need to do :)

**Comment by J0WI** [comment]
As a workaround we could use CSP upgrade-insecure-requests (#5).

**Comment by J0WI** [comment]
For all the header and cert stuff it would be important to know, if our container will run behind a proxy. And we should investigate a lot more in security if not.

**Comment by J0WI** [comment]
We need to set something like:

```
# app/config/parameters.yml
parameters:
    router.request_context.host: mozilla.ch
    router.request_context.scheme: https
```

Sadly we can't test this locally.

**Comment by colinfrei** [comment]
or X_FORWARDED_HOST / X_FORWARDED_PROTO headers?

**Comment by freaktechnik** [comment]
The letsencrypt docker container is just to run the letsencrypt tool, which isn't too helpful here. The most reasonnable solution I'd know of would be to mount the certs from outside the container, since they are a secret thing like API keys. This should be possible for community IT to do without us doing any adjustments to the container - it seems they've already managed to do exactly that for the mozilla.community subdomain they gave us. So I'm not sure there's much to do for us here.

Edit: the mixed content problems should be resolved within mozillach/mozilla.ch
Edit2: Looked at our twig template, and in theory everything should get https if our php app gets talked to over https too. Trouble is, the currently deployed container doesn't even have the HTTPS port opened, so it must be the router that's injecting the https.

**Comment by MichaelKohler** [comment]
> This should be possible for community IT to do without us doing any adjustments to the container - it seems they've already managed to do exactly that for the mozilla.community subdomain they gave us. 

I just asked this question (we probably will also need to specify what cert this will be, since the domain is currently pointing at my server), will add the response here.

> So I'm not sure there's much to do for us here.

We still need to make sure that we won't be loading any mixed content. This would be fixed automatically once mozilla.ch points to that docker image and it redirects to https, right?

**Comment by MichaelKohler** [comment]
Just got a response, the cert will be attached from outside.

I see the following next steps:
- Fix the remaining bugs we want to have fixed right now (this should happen within the mozilla.ch repo)
- Get a mozilla.ch certificate (do we want to provide a letsencrypt one?)
- Attach it to the container from outside and add the cert (through Community IT)
- Point our A record to the new PaaS

Anything else?

**Comment by freaktechnik** [comment]
If remaining bugs includes making the container work with https and external certificates that'd be all... It will also mean, that running the container gets more complicated, since it needs a valid cert config.

**Comment by MichaelKohler** [comment]
@freaktechnik what would you suggest here? Making it more complicated doesn't sound nice :/

**Comment by freaktechnik** [comment]
Since we don't primarily use docker for testing this shouldn't be too big of an issue. However I'm looking into creating simple shell scripts to generate certificates to test the container with.

**Comment by freaktechnik** [comment]
I've pushed a patch to the `travis` branch of mozillach/mozilla.ch. It moves our server to be HTTPS by default. I've also included a little script to actually test the docker container locally, without the need of manually generating testing certs.

**Comment by freaktechnik** [comment]
This is fixed on master.
